package net.megalogamingt4f.megalosmod.item;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.megalogamingt4f.megalosmod.MegalosMod;
import net.megalogamingt4f.megalosmod.tab.MegalosModItemGroup;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;

import net.minecraft.util.registry.Registry;

public class ModItems {
    //Metallurgy
    public static final Item ALUMINIUM_INGOT = registerItem("aluminium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ALUMINIUM_NUGGET = registerItem("aluminium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ALUMINIUM_DUST = registerItem("aluminium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ALUMINIUM_RAW = registerItem("raw_aluminium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ANTIMONY_INGOT = registerItem("antimony_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ANTIMONY_NUGGET = registerItem("antimony_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ANTIMONY_DUST = registerItem("antimony_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ANTIMONY_RAW = registerItem("raw_antimony", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ARSENIC_INGOT = registerItem("arsenic_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ARSENIC_NUGGET = registerItem("arsenic_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ARSENIC_DUST = registerItem("arsenic_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ARSENIC_RAW = registerItem("raw_arsenic", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BARIUM_INGOT = registerItem("barium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BARIUM_NUGGET = registerItem("barium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BARIUM_DUST = registerItem("barium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BARIUM_RAW = registerItem("raw_barium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BERYLLIUM_INGOT = registerItem("beryllium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BERYLLIUM_NUGGET = registerItem("beryllium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BERYLLIUM_DUST = registerItem("beryllium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BERYLLIUM_RAW = registerItem("raw_beryllium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BISMUTH_INGOT = registerItem("bismuth_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BISMUTH_NUGGET = registerItem("bismuth_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BISMUTH_DUST = registerItem("bismuth_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item BISMUTH_RAW = registerItem("raw_bismuth", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CADMIUM_INGOT = registerItem("cadmium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CADMIUM_NUGGET = registerItem("cadmium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CADMIUM_DUST = registerItem("cadmium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CADMIUM_RAW = registerItem("raw_cadmium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CALCIUM_INGOT = registerItem("calcium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CALCIUM_NUGGET = registerItem("calcium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CALCIUM_DUST = registerItem("calcium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CALCIUM_RAW = registerItem("raw_calcium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CAESIUM_INGOT = registerItem("caesium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CAESIUM_NUGGET = registerItem("caesium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CAESIUM_DUST = registerItem("caesium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CAESIUM_RAW = registerItem("raw_caesium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CHROMIUM_INGOT = registerItem("chromium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CHROMIUM_NUGGET = registerItem("chromium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CHROMIUM_DUST = registerItem("chromium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CHROMIUM_RAW = registerItem("raw_chromium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CINNABAR_INGOT = registerItem("cinnabar_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CINNABAR_NUGGET = registerItem("cinnabar_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CINNABAR_DUST = registerItem("cinnabar_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item CINNABAR_RAW = registerItem("raw_cinnabar", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item COBALT_INGOT = registerItem("cobalt_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item COBALT_NUGGET = registerItem("cobalt_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item COBALT_DUST = registerItem("cobalt_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item COBALT_RAW = registerItem("raw_cobalt", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GERMANIUM_INGOT = registerItem("germanium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GERMANIUM_NUGGET = registerItem("germanium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GERMANIUM_DUST = registerItem("germanium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GERMANIUM_RAW = registerItem("raw_germanium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GALLIUM_INGOT = registerItem("gallium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GALLIUM_NUGGET = registerItem("gallium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GALLIUM_DUST = registerItem("gallium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GALLIUM_RAW = registerItem("raw_gallium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item HAFNIUM_INGOT = registerItem("hafnium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item HAFNIUM_NUGGET = registerItem("hafnium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item HAFNIUM_DUST = registerItem("hafnium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item HAFNIUM_RAW = registerItem("raw_hafnium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item INDIUM_INGOT = registerItem("indium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item INDIUM_NUGGET = registerItem("indium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item INDIUM_DUST = registerItem("indium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item INDIUM_RAW = registerItem("raw_indium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item IRIDIUM_INGOT = registerItem("iridium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item IRIDIUM_NUGGET = registerItem("iridium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item IRIDIUM_DUST = registerItem("iridium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item IRIDIUM_RAW = registerItem("raw_iridium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LEAD_INGOT = registerItem("lead_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LEAD_NUGGET = registerItem("lead_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LEAD_DUST = registerItem("lead_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LEAD_RAW = registerItem("raw_lead", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LITHIUM_INGOT = registerItem("lithium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LITHIUM_NUGGET = registerItem("lithium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LITHIUM_DUST = registerItem("lithium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item LITHIUM_RAW = registerItem("raw_lithium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MAGNESIUM_INGOT = registerItem("magnesium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MAGNESIUM_NUGGET = registerItem("magnesium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MAGNESIUM_DUST = registerItem("magnesium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MAGNESIUM_RAW = registerItem("raw_magnesium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MANGANESE_INGOT = registerItem("manganese_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MANGANESE_NUGGET = registerItem("manganese_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MANGANESE_DUST = registerItem("manganese_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MANGANESE_RAW = registerItem("raw_manganese", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MOLYBDENUM_INGOT = registerItem("molybdenum_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MOLYBDENUM_NUGGET = registerItem("molybdenum_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MOLYBDENUM_DUST = registerItem("molybdenum_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item MOLYBDENUM_RAW = registerItem("raw_molybdenum", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NICKEL_INGOT = registerItem("nickel_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NICKEL_NUGGET = registerItem("nickel_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NICKEL_DUST = registerItem("nickel_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NICKEL_RAW = registerItem("raw_nickel", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NIOBIUM_INGOT = registerItem("niobium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NIOBIUM_NUGGET = registerItem("niobium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NIOBIUM_DUST = registerItem("niobium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item NIOBIUM_RAW = registerItem("raw_niobium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item OSMIUM_INGOT = registerItem("osmium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item OSMIUM_NUGGET = registerItem("osmium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item OSMIUM_DUST = registerItem("osmium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item OSMIUM_RAW = registerItem("raw_osmium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PALLADIUM_INGOT = registerItem("palladium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PALLADIUM_NUGGET = registerItem("palladium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PALLADIUM_DUST = registerItem("palladium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PALLADIUM_RAW = registerItem("raw_palladium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PHOSPHORUS_INGOT = registerItem("phosphorus_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PHOSPHORUS_NUGGET = registerItem("phosphorus_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PHOSPHORUS_DUST = registerItem("phosphorus_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PHOSPHORUS_RAW = registerItem("raw_phosphorus", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PLATINUM_INGOT = registerItem("platinum_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PLATINUM_NUGGET = registerItem("platinum_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PLATINUM_DUST = registerItem("platinum_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item PLATINUM_RAW = registerItem("raw_platinum", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item POTASSIUM_INGOT = registerItem("potassium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item POTASSIUM_NUGGET = registerItem("potassium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item POTASSIUM_DUST = registerItem("potassium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item POTASSIUM_RAW = registerItem("raw_potassium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHENIUM_INGOT = registerItem("rhenium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHENIUM_NUGGET = registerItem("rhenium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHENIUM_DUST = registerItem("rhenium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHENIUM_RAW = registerItem("raw_rhenium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHODIUM_INGOT = registerItem("rhodium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHODIUM_NUGGET = registerItem("rhodium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHODIUM_DUST = registerItem("rhodium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RHODIUM_RAW = registerItem("raw_rhodium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUBIDIUM_INGOT = registerItem("rubidium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUBIDIUM_NUGGET = registerItem("rubidium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUBIDIUM_DUST = registerItem("rubidium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUBIDIUM_RAW = registerItem("raw_rubidium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUTHENIUM_INGOT = registerItem("ruthenium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUTHENIUM_NUGGET = registerItem("ruthenium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUTHENIUM_DUST = registerItem("ruthenium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item RUTHENIUM_RAW = registerItem("raw_ruthenium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SCANDIUM_INGOT = registerItem("scandium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SCANDIUM_NUGGET = registerItem("scandium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SCANDIUM_DUST = registerItem("scandium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SCANDIUM_RAW = registerItem("raw_scandium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SELENIUM_INGOT = registerItem("selenium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SELENIUM_NUGGET = registerItem("selenium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SELENIUM_DUST = registerItem("selenium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SELENIUM_RAW = registerItem("raw_selenium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILICON_INGOT = registerItem("silicon_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILICON_NUGGET = registerItem("silicon_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILICON_DUST = registerItem("silicon_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILICON_RAW = registerItem("raw_silicon", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILVER_INGOT = registerItem("silver_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILVER_NUGGET = registerItem("silver_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILVER_DUST = registerItem("silver_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SILVER_RAW = registerItem("raw_silver", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SODIUM_INGOT = registerItem("sodium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SODIUM_NUGGET = registerItem("sodium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SODIUM_DUST = registerItem("sodium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item SODIUM_RAW = registerItem("raw_sodium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item STRONTIUM_INGOT = registerItem("strontium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item STRONTIUM_NUGGET = registerItem("strontium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item STRONTIUM_DUST = registerItem("strontium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item STRONTIUM_RAW = registerItem("raw_strontium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TANTALUM_INGOT = registerItem("tantalum_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TANTALUM_NUGGET = registerItem("tantalum_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TANTALUM_DUST = registerItem("tantalum_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TANTALUM_RAW = registerItem("raw_tantalum", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TECHNETIUM_INGOT = registerItem("technetium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TECHNETIUM_NUGGET = registerItem("technetium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TECHNETIUM_DUST = registerItem("technetium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TECHNETIUM_RAW = registerItem("raw_technetium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TELLURIUM_INGOT = registerItem("tellurium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TELLURIUM_NUGGET = registerItem("tellurium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TELLURIUM_DUST = registerItem("tellurium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TELLURIUM_RAW = registerItem("raw_tellurium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item THALLIUM_INGOT = registerItem("thallium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item THALLIUM_NUGGET = registerItem("thallium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item THALLIUM_DUST = registerItem("thallium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item THALLIUM_RAW = registerItem("raw_thallium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TIN_INGOT = registerItem("tin_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TIN_NUGGET = registerItem("tin_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TIN_DUST = registerItem("tin_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TIN_RAW = registerItem("raw_tin", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TITANIUM_INGOT = registerItem("titanium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TITANIUM_NUGGET = registerItem("titanium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TITANIUM_DUST = registerItem("titanium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TITANIUM_RAW = registerItem("raw_titanium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TUNGSTEN_INGOT = registerItem("tungsten_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TUNGSTEN_NUGGET = registerItem("tungsten_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TUNGSTEN_DUST = registerItem("tungsten_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item TUNGSTEN_RAW = registerItem("raw_tungsten", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item VANADIUM_INGOT = registerItem("vanadium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item VANADIUM_NUGGET = registerItem("vanadium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item VANADIUM_DUST = registerItem("vanadium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item VANADIUM_RAW = registerItem("raw_vanadium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item YTTRIUM_INGOT = registerItem("yttrium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item YTTRIUM_NUGGET = registerItem("yttrium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item YTTRIUM_DUST = registerItem("yttrium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item YTTRIUM_RAW = registerItem("raw_yttrium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZINC_INGOT = registerItem("zinc_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZINC_NUGGET = registerItem("zinc_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZINC_DUST = registerItem("zinc_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZINC_RAW = registerItem("raw_zinc", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZIRCONIUM_INGOT = registerItem("zirconium_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZIRCONIUM_NUGGET = registerItem("zirconium_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZIRCONIUM_DUST = registerItem("zirconium_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item ZIRCONIUM_RAW = registerItem("raw_zirconium", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));

    //Alloy
    public static final Item STEEL_INGOT = registerItem("steel_ingot", new Item(new FabricItemSettings().group(MegalosModItemGroup.ALLOY)));
    public static final Item STEEL_NUGGET = registerItem("steel_nugget", new Item(new FabricItemSettings().group(MegalosModItemGroup.ALLOY)));
    public static final Item STEEL_DUST = registerItem("steel_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.ALLOY)));

    //Extras

    public static final Item COPPER_DUST = registerItem("copper_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item IRON_DUST = registerItem("iron_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item GOLD_DUST = registerItem("gold_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));
    public static final Item COAL_DUST = registerItem("coal_dust", new Item(new FabricItemSettings().group(MegalosModItemGroup.METALLURGY)));

    //Dendrology

    public static final Item SAPLING_ASH = registerItem("sapling_ash", new Item(new FabricItemSettings().group(MegalosModItemGroup.DENDROLOGY)));

    //Gastronomy
    //Technology

private static Item registerItem(String name, Item item){
    return Registry.register(Registry.ITEM, new Identifier(MegalosMod.MOD_ID, name), item);
}

    public static void registerModItems(){
        MegalosMod.LOGGER.info("Registring Mod Items for " + MegalosMod.MOD_ID);
    }
}
